name: Trigger Homebrew Tap Update

on:
  release:
    types: [published]

jobs:
  trigger-homebrew:
    name: Notify Homebrew Tap
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Pork0594/homebrew-WizERD
          event-type: pypi_updated
          client-payload: '{"version": "${{ github.event.release.tag_name }}"}'
